-- Prisma migration removed. Project migrated to Mongoose.
-- Original SQL migration content removed from repository to avoid confusion.
-- If you need the original migration SQL, retrieve it from the Git history.
